[package]
name = "base-alloy-flz"
description = "Tiny FastLZ compression library for L2 transaction cost estimation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
fastlz = { version = "0.1.0", optional = true }

[features]
default = []
compress = ["dep:fastlz"]
decompress = ["dep:fastlz"]
