[package]
name = "base-node-service"
description = "An implementation of the OP Stack consensus node service"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
base-gossip.workspace = true
base-disc.workspace = true
base-engine.workspace = true
base-sources.workspace = true
base-genesis.workspace = true
base-derive.workspace = true
base-protocol.workspace = true
base-providers-alloy.workspace = true
base-rpc = { workspace = true, features = ["client"] }
base-peers.workspace = true
base-macros.workspace = true

# rollup-boost
rollup-boost.workspace = true

# alloy
alloy-chains.workspace = true
alloy-signer.workspace = true
alloy-signer-local.workspace = true
alloy-primitives.workspace = true
alloy-rpc-client.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["jwt", "serde"] }
alloy-provider = { workspace = true, features = ["reqwest", "reqwest-rustls-tls", "hyper", "hyper-tls"] }
alloy-eips.workspace = true
alloy-transport.workspace = true
alloy-transport-http = { workspace = true, features = ["reqwest", "reqwest-rustls-tls", "hyper", "hyper-tls", "jwt-auth"] }

# op-alloy
base-alloy-network.workspace = true
base-alloy-rpc-types-engine = { workspace = true, features = ["std"] }
base-alloy-provider.workspace = true

# general
url.workspace = true
libp2p.workspace = true
libp2p-stream.workspace = true
discv5.workspace = true
futures.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
async-trait.workspace = true
async-stream.workspace = true
tokio-stream.workspace = true
strum = { workspace = true, features = ["derive"] }
backon.workspace = true
derive_more = { workspace = true, features = ["debug", "display", "eq", "from_str", "constructor"] }
jsonrpsee = { workspace = true, features = ["server", "http-client"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tower.workspace = true
http-body-util.workspace = true

# metrics
metrics = { workspace = true, optional = true }

[dev-dependencies]
rstest.workspace = true
arbitrary.workspace = true
rand.workspace = true
anyhow.workspace = true
backon.workspace = true
http = "1"
mockall.workspace = true
alloy-primitives = { workspace = true, features = ["k256"] }
alloy-rpc-types-engine = { workspace = true, features = ["arbitrary"] }
alloy-consensus = { workspace = true, features = ["arbitrary"] }
base-alloy-consensus = { workspace = true, features = ["arbitrary", "k256"] }
base-derive = { workspace = true, features = ["test-utils"] }

[features]
default = []
metrics = [
	"dep:metrics",
	"base-derive/metrics",
	"base-disc/metrics",
	"base-engine/metrics",
	"base-gossip/metrics",
	"base-providers-alloy/metrics",
	"base-rpc/metrics",
	"libp2p/metrics",
]
